[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "fastafood"
version = "0.2.0"
description = "A Python package to cook DNA variants (SNPs, deletions, duplications)"
authors = [
    { name="Luc Thomès" }
]
readme = "README.md"
requires-python = ">=3.9"

dependencies = []

[project.urls]
"Homepage" = "https://github.com/lthomes/fastafood"
"Repository" = "https://github.com/lthomes/fastafood"

[project.scripts]
fastafood = "fastafood.cli:main"